# create the restart-nginx.yml handler file located at roles/nginx-php/handlers/restart-nginx.yml to restart nginx when necessary. 
# Open the restart-nginx.yml file and modify it as follows:


- name: Example playbook to restart nginx
  hosts: all
  tasks:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        
        
# Now test it using the nginx-php.yml playbook. Run the following command to execute the playbook:        
# ansible-playbook playbooks/nginx-php.yml
